### ISSUE TITLE
91.189.88.142 80 software has been removed

### ISSUE THREAD

**Issue by askfiy** [Haru0517/DeepSentiBank-builder#7]
When running docker-compose build or docker-compose up -d, it will give a lot of error prompts, such as:

```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libx/libxi/libxi-dev_1.7.6-1_amd64.deb  Connection failed [IP: 91.189.88.152 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/x/x11proto-randr/x11proto-randr-dev_1.5.0-1_all.deb  Connection failed [IP: 91.189.88.152 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libx/libxrandr/libxrandr-dev_1.5.0-1_amd64.deb  Connection failed [IP: 91.189.88.152 80]
```

When the browser accesses 91.189.88.142:80, I find that these software have been cleaned up, please tell me what should I do to make docker run.

**Comment by ychikazawa** [comment]
It doesn't reproduce in my environment.
Do you live in China?
The following issue may be related to your case.
https://askubuntu.com/questions/1076584/apt-get-update-connection-failed-but-wget-is-ok

**Comment by askfiy** [comment]
> It doesn't reproduce in my environment. Do you live in China? The following issue may be related to your case. https://askubuntu.com/questions/1076584/apt-get-update-connection-failed-but-wget-is-ok

I tried the solution you gave, but the problem persists. I am indeed in China, but I use a VPN.

the error in the following figure is an example:

![图片](https://user-images.githubusercontent.com/81478335/154847994-fd0f79f5-0e64-4707-8c1d-e315600b1425.png)

I opened my browser and went to the resource at 91.189.88.142:80 to try to find this resource, but it was indeed taken down.

![图片](https://user-images.githubusercontent.com/81478335/154848061-f50b946f-c1a4-44e3-851e-3bb1ebb57c52.png)

So I don't think it has anything to do with being in that region, the problem is with the source, which has been updated.

**Comment by ychikazawa** [comment]
Please try to update `docker/Dockerfile` to following code and run.

```
FROM ubuntu:16.04

RUN apt-get update
```

if this issue still occurs, the problem must be caused by `apt-get update`, similar to the above site.

**Comment by askfiy** [comment]
> Please try to update `docker/Dockerfile` to following code and run.
> 
> ```
> FROM ubuntu:16.04
> 
> RUN apt-get update
> ```
> 
> if this issue still occurs, the problem must be caused by `apt-get update`, similar to the above site.

In order to achieve a 100% match of the environment, I tried the ubtu16.04 virtual machine.

But unfortunately the problem still can not be solved, I think this is the problem of the source.

Is it possible to rebuild the dockerfile so that more developers can use it later?

**Comment by ychikazawa** [comment]
Thank you for the verification.
It's no longer a problem with my project, as you get the same error after running this.
Not only my project, but any time you update ubuntu apt-get in docker in your environment, you will have this issue.

It is working completely fine in my environment.
And I can't confirm this issue reported to occur in China.
Therefore, it is difficult for me to solve it.

You will need to edit your Dockerfile or create an empty docker environment and run commands in it to address the issue.
The following document may be of help.
https://github.com/xianhegithub/quantitative_trading/wiki/Install-Docker-in-Mainland-China-%28Ubuntu-16.04-LTS%29
